name: nuxt_deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PROCESS_NAME: nuxt-app
      PROJECT_PATH: /var/www/ecommerce/frontend
      SSH_HOST: ${{ secrets.SSH_HOST }}
      SSH_PASSWORD: ${{ secrets.SSH_PASSWORD }}
      SSH_USER: ${{ secrets.SSH_USER }}
      ECOSYSTEM_PATH: ./ecosystem.config.cjs
    outputs:
      commit_message: ${{ steps.get_commit_message.outputs.commit_message }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Get Commit Message
        id: get_commit_message
        run: |
          COMMIT_MESSAGE=$(git log -1 --pretty=format:"%s")
          echo "::set-output name=commit_message::$COMMIT_MESSAGE"

      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version: '22'

      - name: Add npm and yarn global packages to PATH
        run: |
          echo "PATH=${HOME}/.npm-global/bin:${HOME}/.yarn/bin:$(npm config get prefix)/bin:$PATH" >> $GITHUB_ENV

      - name: Install yarn
        run: npm install -g yarn

      - name: Install pm2
        run: npm install -g pm2

      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: Deploy to server
        id: deploy
        run: |
          echo "Deploying..."
          sshpass -p "$SSH_PASSWORD" ssh $SSH_USER@$SSH_HOST << EOF
            cd ${{ env.PROJECT_PATH }}
            # Pull từ git về 
            git checkout -- yarn.lock package-lock.json package.json
            git pull 
          
            # Cài đặt các dependencies
            yarn install
            yarn build

            # Check process
            if pm2 list | grep '${{ env.PROCESS_NAME }}'; then
              echo "Dừng và xoá process..."
              pm2 stop ${{ env.PROCESS_NAME }}
              pm2 delete ${{ env.PROCESS_NAME }}
            else
              echo "Không có process hoạt động."
            fi

            # Chạy pm2
            pm2 start ${{ env.ECOSYSTEM_PATH }} --env production

            echo 'Deploy thành công!'
          EOF